/*
  Copyright (c) 2006-2007 Fusion Project Team
	Portions Copyright (C) Scott Bilas, 2000

  This software is provided 'as-is', without any express or implied warranty.
	In noevent will the authors be held liable for any damages arising from the
	use of this software.

  Permission is granted to anyone to use this software for any purpose,
	including commercial applications, and to alter it and redistribute it
	freely, subject to the following restrictions:

    1. The origin of this software must not be misrepresented; you must not
		claim that you wrote the original software. If you use this software in a
		product, an acknowledgment in the product documentation would be
		appreciated but is not required.

    2. Altered source versions must be plainly marked as such, and must not
		be misrepresented as being the original software.

    3. This notice may not be removed or altered from any source distribution.

		
	File Author(s):

		Elliot Hayward

		Scott Bilas (original)
*/

#ifndef H_FusionEngine_Singleton
#define H_FusionEngine_Singleton

#if _MSC_VER > 1000
#	pragma once

#	pragma warning(push)
// Turn off warnings generated by this singleton implementation
#	pragma warning (disable : 4311)
#	pragma warning (disable : 4312)
#endif

#include "FusionAssert.h"
#include <type_traits>

namespace FusionEngine
{

 /*!
	* \brief
	* Template class for creating singleton classes.
	*/
	template<typename T>
	class Singleton
	{
		//! The instance
		static T* ms_Singleton;

	public:
		//! Constructor
		Singleton()
		{
			FSN_ASSERT( !ms_Singleton );
			ms_Singleton = static_cast< T* >( this );
		}

		//! Destructor
		virtual ~Singleton()
		{
			FSN_ASSERT( ms_Singleton != nullptr );
			ms_Singleton = 0;
		}

	public:
		//! Returns the static instance of singleton
		static T& getSingleton()
		{
			FSN_ASSERT( ms_Singleton != NULL );
			return *ms_Singleton;
		}
		//! Returns a pointer to the static instance of singleton
		static T* getSingletonPtr()
		{
			return ms_Singleton;
		}

	};
	// Make sure ms_Singleton is initialized
	template <typename T> T* Singleton <T>::ms_Singleton = nullptr;


 /*!
	* \brief
	* Template class for creating weak singleton classes.
	*
	* Weak singletons can have more than one instance, and only
	* the first one is stored as the singleton.
	*/
	template<typename T>
	class WeakSingleton
	{
	public:
		//! Constructor
		WeakSingleton()
		{
			if (ms_Singleton == nullptr)
				ms_Singleton = static_cast< T* >( this );
		}
		//! Destructor
		virtual ~WeakSingleton()
		{
			if (ms_Singleton == this)
				ms_Singleton = nullptr;
		}

	public:
		//! Returns the static instance of singleton
		static T& getSingleton()
		{
			FSN_ASSERT(ms_Singleton);
			return *ms_Singleton;
		}
		//! Returns a pointer to the static instance of singleton
		static T* getSingletonPtr()
		{
			return ms_Singleton;
		}

	private:
		//! The instance
		static T *ms_Singleton;
	};

	template <typename T> T* WeakSingleton<T>::ms_Singleton = nullptr;

}

#if _MSC_VER > 1000
#	pragma warning(pop)
#endif

#endif